import os
import re
import requests


QASE_BASE = "https://api.qase.io/v1"


def _headers():
    token = os.getenv("QASE_API_TOKEN")
    if not token:
        raise ValueError("QASE_API_TOKEN is not set in .env")
    return {"Token": token, "Accept": "application/json", "Content-Type": "application/json"}


def _project_code():
    code = os.getenv("QASE_PROJECT_CODE", "").strip()
    if not code:
        raise ValueError("QASE_PROJECT_CODE is not set in .env")
    return code


def get_suites():
    """Fetch all suites for the project."""
    code = _project_code()
    resp = requests.get(f"{QASE_BASE}/suite/{code}?limit=100", headers=_headers(), timeout=10)
    resp.raise_for_status()
    suites = resp.json().get("result", {}).get("entities", [])
    return [{"id": s["id"], "title": s["title"], "parent_id": s.get("parent_id")} for s in suites]


def create_suite(title, description="", parent_id=None):
    """Create a new test suite and return its ID."""
    code = _project_code()
    payload = {"title": title}
    if description:
        payload["description"] = description
    if parent_id:
        payload["parent_id"] = int(parent_id)
    resp = requests.post(f"{QASE_BASE}/suite/{code}", json=payload, headers=_headers(), timeout=10)
    resp.raise_for_status()
    return resp.json()["result"]["id"]


def create_test_case(suite_id, title, preconditions="", steps=None, expected_result="", priority=2):
    """Create a single test case in the given suite."""
    code = _project_code()

    qase_steps = []
    if steps:
        for i, step in enumerate(steps):
            qase_steps.append({
                "action": step.get("action", ""),
                "expected_result": step.get("expected_result", ""),
            })

    payload = {
        "title": title[:255],
        "suite_id": suite_id,
        "priority": priority,
        "automation": 0,  # manual
        "steps_type": "classic",
    }

    if preconditions:
        payload["preconditions"] = preconditions
    if qase_steps:
        payload["steps"] = qase_steps
    if expected_result and not qase_steps:
        payload["description"] = f"**Expected Result:**\n{expected_result}"

    resp = requests.post(f"{QASE_BASE}/case/{code}", json=payload, headers=_headers(), timeout=10)
    resp.raise_for_status()
    return resp.json()["result"]["id"]


def parse_test_cases_markdown(markdown):
    """Parse AI-generated test cases markdown into structured data."""
    cases = []

    tc_blocks = re.split(r"###\s+TC-\d+:\s*", markdown)
    tc_titles = re.findall(r"###\s+TC-\d+:\s*(.+)", markdown)

    for i, block in enumerate(tc_blocks[1:]):
        if i >= len(tc_titles):
            break

        title = tc_titles[i].strip()

        priority_match = re.search(r"\*\*Priority:\*\*\s*(High|Medium|Low)", block, re.IGNORECASE)
        priority_map = {"high": 1, "medium": 2, "low": 3}
        priority = priority_map.get(priority_match.group(1).lower(), 2) if priority_match else 2

        preconditions = ""
        pre_match = re.search(r"\*\*Preconditions?:\*\*\s*\n((?:[-•]\s*.+\n?)+)", block)
        if pre_match:
            preconditions = pre_match.group(1).strip()

        steps = []
        steps_match = re.search(r"\*\*Steps:\*\*\s*\n((?:\d+\.\s*.+\n?)+)", block)
        if steps_match:
            step_lines = re.findall(r"\d+\.\s*(.+)", steps_match.group(1))
            for line in step_lines:
                steps.append({"action": line.strip(), "expected_result": ""})

        expected = ""
        exp_match = re.search(r"\*\*Expected Result:\*\*\s*\n((?:[-•]\s*.+\n?)+)", block)
        if exp_match:
            expected = exp_match.group(1).strip()

        if steps and expected:
            steps[-1]["expected_result"] = expected

        cases.append({
            "title": title,
            "priority": priority,
            "preconditions": preconditions,
            "steps": steps,
            "expected_result": expected,
        })

    return cases


def push_test_cases_to_qase(markdown, suite_name, suite_id=None, parent_id=None):
    """Parse markdown test cases and push them to Qase.

    If suite_id is provided, uses that suite.
    Otherwise creates a new suite with suite_name under parent_id.
    Returns summary of created cases.
    """
    cases = parse_test_cases_markdown(markdown)
    if not cases:
        raise ValueError("Could not parse any test cases from the generated output.")

    if not suite_id:
        suite_id = create_suite(suite_name, description="Auto-generated by QA Copilot", parent_id=parent_id)

    created = []
    for tc in cases:
        case_id = create_test_case(
            suite_id=suite_id,
            title=tc["title"],
            preconditions=tc["preconditions"],
            steps=tc["steps"],
            expected_result=tc["expected_result"],
            priority=tc["priority"],
        )
        created.append({"id": case_id, "title": tc["title"]})

    code = _project_code()
    return {
        "suite_id": suite_id,
        "suite_url": f"https://app.qase.io/project/{code}/suite/{suite_id}",
        "cases_created": len(created),
        "cases": created,
    }
